# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do | config |
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "server-mrf"
  config.vm.provider "virtualbox" do | vb |
    vb.name = "Ubuntu Server"
    vb.memory = 2048
    vb.cpus = 2
  end  
end
