# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do | config |
  config.vm.define "server" do | m1 |
    m1.vm.box = "gusztavvargadr/windows-server-2019-standard"
    m1.vm.hostname = "windows-server"
    m1.vm.provider "virtualbox" do | vb |
      vb.name = "server-mrf"
      vb.memory = 4096
      vb.cpus = 4
    end
  end


  config.vm.define "cliente" do | m2 |
    m2.vm.box = "gusztavvargadr/windows-10"
    m2.vm.hostname = "windows-cliente"
    m2.vm.provider "virtualbox" do | vb |
      vb.name = "cliente-mrf"
      vb.memory = 2048
      vb.cpus = 2
    end
  end
end