# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do | config |
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "Web-server"
  config.vm.network "private_network", ip: "192.168.200.10"
  config.vm.network "public_network", ip: "10.9.9.10"
  config.vm.network "forwarded_port, guest: 80, host:8080"
  config.vm.provider "virtualbox" do | vb |
    vb.name = "web-mrf"
    vb.memory = 3072
    vb.cpus = 2
  end
end
